In [1]:
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
Vegas = pd.read_csv('vegas.csv')
Vegas.columns = Vegas.columns.str.replace('\.*\s+', '_').str.lower()

/var/folders/xj/j51mz36s00z2vnfq7wp23hxm0000gn/T/ipykernel_99424/3482245113.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  Vegas.columns = Vegas.columns.str.replace('\.*\s+', '_').str.lower()

Group the `DataFrame` by hotel, and pull out a sample group to experiment with.

In [3]:
by_hotel = Vegas.groupby(Vegas.hotel_name)

In [5]:
by_hotel.mean().head(5)

,nr_reviews,nr_hotel_reviews,helpful_votes,score,nr_rooms,member_years
hotel_name,,,,,,
Bellagio Las Vegas,27.71,10.21,24.88,4.21,"3,933.00",3.42
Caesars Palace,38.00,15.29,26.38,4.12,"3,348.00",4.75
Circus Circus Hotel & Casino Las Vegas,29.21,7.79,18.50,3.21,"3,773.00",3.83
Encore at wynn Las Vegas,57.17,16.33,36.75,4.54,"2,034.00",4.75
Excalibur Hotel & Casino,45.58,22.12,31.75,3.71,"3,981.00",4.50

In [6]:
by_hotel = Vegas.groupby('hotel_name')

In [7]:
by_hotel.score.mean().head(5)

hotel_name
Bellagio Las Vegas                       4.21
Caesars Palace                           4.12
Circus Circus Hotel & Casino Las Vegas   3.21
Encore at wynn Las Vegas                 4.54
Excalibur Hotel & Casino                 3.71
Name: score, dtype: float64

In [9]:
by_hotel.hotel_name.value_counts().index.values

array([('Bellagio Las Vegas', 'Bellagio Las Vegas'),
       ('Caesars Palace', 'Caesars Palace'),
       ('Circus Circus Hotel & Casino Las Vegas', 'Circus Circus Hotel & Casino Las Vegas'),
       ('Encore at wynn Las Vegas', 'Encore at wynn Las Vegas'),
       ('Excalibur Hotel & Casino', 'Excalibur Hotel & Casino'),
       ('Hilton Grand Vacations at the Flamingo', 'Hilton Grand Vacations at the Flamingo'),
       ('Hilton Grand Vacations on the Boulevard', 'Hilton Grand Vacations on the Boulevard'),
       ("Marriott's Grand Chateau", "Marriott's Grand Chateau"),
       ('Monte Carlo Resort&Casino', 'Monte Carlo Resort&Casino'),
       ('Paris Las Vegas', 'Paris Las Vegas'),
       ('The Cosmopolitan Las Vegas', 'The Cosmopolitan Las Vegas'),
       ('The Cromwell', 'The Cromwell'),
       ('The Palazzo Resort Hotel Casino', 'The Palazzo Resort Hotel Casino'),
       ('The Venetian Las Vegas Hotel', 'The Venetian Las Vegas Hotel'),
       ('The Westin las Vegas Hotel Casino & Spa', 'The Westin las Vegas Hotel Casino & Spa'),
       ('Treasure Island- TI Hotel & Casino', 'Treasure Island- TI Hotel & Casino'),
       ('Tropicana Las Vegas - A Double Tree by Hilton Hotel', 'Tropicana Las Vegas - A Double Tree by Hilton Hotel'),
       ('Trump International Hotel Las Vegas', 'Trump International Hotel Las Vegas'),
       ('Tuscany Las Vegas Suites & Casino', 'Tuscany Las Vegas Suites & Casino'),
       ('Wyndham Grand Desert', 'Wyndham Grand Desert'),
       ('Wynn Las Vegas', 'Wynn Las Vegas')], dtype=object)

In [15]:
sample_group = by_hotel.get_group('Caesars Palace')
sample_group.head(5)

,user_country,nr_reviews,nr_hotel_reviews,helpful_votes,score,period_of_stay,traveler_type,pool,gym,tennis_court,spa,casino,free_internet,hotel_name,hotel_stars,nr_rooms,user_continent,member_years,review_month,review_weekday
120,USA,50,14,24,5,Dec-Feb,Friends,YES,YES,NO,YES,YES,YES,Caesars Palace,5,3348,North America,7,January,Wednesday
121,USA,161,33,85,4,Dec-Feb,Couples,YES,YES,NO,YES,YES,YES,Caesars Palace,5,3348,North America,3,January,Friday
122,Puerto Rico,153,38,81,5,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,Caesars Palace,5,3348,North America,10,February,Tuesday
123,Canada,14,3,12,5,Dec-Feb,Families,YES,YES,NO,YES,YES,YES,Caesars Palace,5,3348,North America,2,February,Thursday
124,USA,31,12,10,5,Mar-May,Families,YES,YES,NO,YES,YES,YES,Caesars Palace,5,3348,North America,4,March,Friday

In [16]:
by_hotel = Vegas.groupby(Vegas.hotel_name)
sample_group = by_hotel.get_group(Vegas.hotel_name[0])

In [18]:
sample_group.head(5)

,user_country,nr_reviews,nr_hotel_reviews,helpful_votes,score,period_of_stay,traveler_type,pool,gym,tennis_court,spa,casino,free_internet,hotel_name,hotel_stars,nr_rooms,user_continent,member_years,review_month,review_weekday
0,USA,11,4,13,5,Dec-Feb,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,January,Thursday
1,USA,119,21,75,3,Dec-Feb,Business,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,3,January,Friday
2,USA,36,9,25,5,Mar-May,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,2,February,Saturday
3,UK,14,7,14,4,Mar-May,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,Europe,6,February,Friday
4,Canada,5,5,2,4,Mar-May,Solo,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,7,March,Tuesday

Create a function that takes a group returns two rows of data.  The first row should correspond a random reviewer that gave the highest score to the hotel.  The second should correspond to a random reviewer that gave the lowest score.  Test your function on the sample group.

In [10]:
def top_bottom_reviewers(group):
    max_score = group.score.max()
    min_score = group.score.min()
    good_review = group[group.score == max_score].sample(1)
    bad_review = group[group.score == min_score].sample(1)
    return pd.concat([good_review, bad_review])

In [27]:
def top_bottom_reviewers(gdf):
    max_score = gdf.score.max()
    min_score = gdf.score.min()
    good_review = gdf[gdf.score == max_score].sample(1)
    bad_review = gdf[gdf.score == min_score].sample(1)
    #return good_review + bad_review
    #return bad_review
    return pd.concat([good_review, bad_review])

In [28]:
top_bottom_reviewers(sample_group)

,user_country,nr_reviews,nr_hotel_reviews,helpful_votes,score,period_of_stay,traveler_type,pool,gym,tennis_court,spa,casino,free_internet,hotel_name,hotel_stars,nr_rooms,user_continent,member_years,review_month,review_weekday
0,USA,11,4,13,5,Dec-Feb,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,January,Thursday
16,Canada,8,8,9,1,Sep-Nov,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,4,September,Wednesday

In [11]:
top_bottom_reviewers(sample_group)

,user_country,nr_reviews,nr_hotel_reviews,helpful_votes,score,period_of_stay,traveler_type,pool,gym,tennis_court,spa,casino,free_internet,hotel_name,hotel_stars,nr_rooms,user_continent,member_years,review_month,review_weekday
0,USA,11,4,13,5,Dec-Feb,Friends,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,9,January,Thursday
16,Canada,8,8,9,1,Sep-Nov,Families,NO,YES,NO,NO,YES,YES,Circus Circus Hotel & Casino Las Vegas,3,3773,North America,4,September,Wednesday

Finally, use `apply()` to create a table of top and bottom reviews for all hotels.

In [35]:
by_hotel.apply(top_bottom_reviewers)

                                                       user_country  \
hotel_name
Bellagio Las Vegas                                 436        India
                                                   455     Malaysia
Caesars Palace                                     126       Canada
                                                   131          USA
Circus Circus Hotel & Casino Las Vegas             0            USA
                                                   21    New Zeland
Encore at wynn Las Vegas                           279          USA
                                                   264     Thailand
Excalibur Hotel & Casino                           26        Canada
                                                   39           USA
Hilton Grand Vacations at the Flamingo             364          USA
                                                   363          USA
Hilton Grand Vacations on the Boulevard            310          USA
                                                   297          USA
Marriott's Grand Chateau                           314          USA
                                                   330     Thailand
Monte Carlo Resort&Casino                          54      Scotland
                                                   69         China
Paris Las Vegas                                    457       Canada
                                                   458          USA
The Cosmopolitan Las Vegas                         160           UK
                                                   156          USA
The Cromwell                                       251          USA
                                                   253          USA
The Palazzo Resort Hotel Casino                    170       Canada
                                                   168       Mexico
The Venetian Las Vegas Hotel                       413          USA
                                                   412          USA
The Westin las Vegas Hotel Casino & Spa            484          USA
                                                   502          USA
Treasure Island- TI Hotel & Casino                 92      Thailand
                                                   79     Australia
Tropicana Las Vegas - A Double Tree by Hilton H... 110   New Zeland
                                                   112       Canada
Trump International Hotel Las Vegas                223          USA
                                                   233        Egypt
Tuscany Las Vegas Suites & Casino                  336          USA
                                                   344        India
Wyndham Grand Desert                               390       Canada
                                                   402      Ireland
Wynn Las Vegas                                     198          USA
                                                   208       Canada

                                                        nr_reviews  \
hotel_name
Bellagio Las Vegas                                 436          44
                                                   455          20
Caesars Palace                                     126           5
                                                   131          25
Circus Circus Hotel & Casino Las Vegas             0            11
                                                   21            4
Encore at wynn Las Vegas                           279         333
                                                   264           3
Excalibur Hotel & Casino                           26           30
                                                   39           24
Hilton Grand Vacations at the Flamingo             364          66
                                                   363           3
Hilton Grand Vacations on the Boulevard            310          42
                                                   297          70
Marriott's Grand Chateau                           314          84
                                                   330          18
Monte Carlo Resort&Casino                          54           24
                                                   69            1
Paris Las Vegas                                    457          19
                                                   458           4
The Cosmopolitan Las Vegas                         160          18
                                                   156           6
The Cromwell                                       251           2
                                                   253           4
The Palazzo Resort Hotel Casino                    170           4
                                                   168          28
The Venetian Las Vegas Hotel                       413          19
                                                   412           9
The Westin las Vegas Hotel Casino & Spa            484          33
                                                   502           9
Treasure Island- TI Hotel & Casino                 92            4
                                                   79           16
Tropicana Las Vegas - A Double Tree by Hilton H... 110           8
                                                   112          27
Trump International Hotel Las Vegas                223           1
                                                   233           2
Tuscany Las Vegas Suites & Casino                  336         167
                                                   344           1
Wyndham Grand Desert                               390          69
                                                   402          76
Wynn Las Vegas                                     198         125
                                                   208          12

                                                        nr_hotel_reviews  \
hotel_name
Bellagio Las Vegas                                 436                35
                                                   455                18
Caesars Palace                                     126                 5
                                                   131                22
Circus Circus Hotel & Casino Las Vegas             0                   4
                                                   21                  3
Encore at wynn Las Vegas                           279                58
                                                   264                 3
Excalibur Hotel & Casino                           26                 12
                                                   39                  6
Hilton Grand Vacations at the Flamingo             364                13
                                                   363                 3
Hilton Grand Vacations on the Boulevard            310                11
                                                   297                25
Marriott's Grand Chateau                           314                18
                                                   330                 9
Monte Carlo Resort&Casino                          54                 10
                                                   69                  0
Paris Las Vegas                                    457                 3
                                                   458                 4
The Cosmopolitan Las Vegas                         160                 9
                                                   156                 4
The Cromwell                                       251                 0
                                                   253                 0
The Palazzo Resort Hotel Casino                    170                 0
                                                   168                23
The Venetian Las Vegas Hotel                       413                 7
                                                   412                 3
The Westin las Vegas Hotel Casino & Spa            484                11
                                                   502                 6
Treasure Island- TI Hotel & Casino                 92                  3
                                                   79                 13
Tropicana Las Vegas - A Double Tree by Hilton H... 110                 7
                                                   112                 0
Trump International Hotel Las Vegas                223                 0
                                                   233                 0
Tuscany Las Vegas Suites & Casino                  336                71
                                                   344                 0
Wyndham Grand Desert                               390                22
                                                   402                27
Wynn Las Vegas                                     198                35
                                                   208                 7

                                                        helpful_votes  score  \
hotel_name
Bellagio Las Vegas                                 436             53      5
                                                   455             19      2
Caesars Palace                                     126              4      5
                                                   131             36      1
Circus Circus Hotel & Casino Las Vegas             0               13      5
                                                   21               3      1
Encore at wynn Las Vegas                           279            200      5
                                                   264             20      1
Excalibur Hotel & Casino                           26              17      5
                                                   39               9      2
Hilton Grand Vacations at the Flamingo             364             21      5
                                                   363              8      2
Hilton Grand Vacations on the Boulevard            310             36      5
                                                   297             19      1
Marriott's Grand Chateau                           314             36      5
                                                   330              8      3
Monte Carlo Resort&Casino                          54              13      5
                                                   69               2      1
Paris Las Vegas                                    457             12      5
                                                   458              2      2
The Cosmopolitan Las Vegas                         160             10      5
                                                   156             14      1
The Cromwell                                       251              1      5
                                                   253             16      1
The Palazzo Resort Hotel Casino                    170              4      5
                                                   168             31      3
The Venetian Las Vegas Hotel                       413              5      5
                                                   412             13      3
The Westin las Vegas Hotel Casino & Spa            484             12      5
                                                   502              5      2
Treasure Island- TI Hotel & Casino                 92               1      5
                                                   79              16      3
Tropicana Las Vegas - A Double Tree by Hilton H... 110              3      5
                                                   112              9      1
Trump International Hotel Las Vegas                223              1      5
                                                   233             15      1
Tuscany Las Vegas Suites & Casino                  336            119      5
                                                   344              3      2
Wyndham Grand Desert                               390             38      5
                                                   402             32      3
Wynn Las Vegas                                     198             48      5
                                                   208             11      2

                                                       period_of_stay  \
hotel_name
Bellagio Las Vegas                                 436        Mar-May
                                                   455        Dec-Feb
Caesars Palace                                     126        Mar-May
                                                   131        Jun-Aug
Circus Circus Hotel & Casino Las Vegas             0          Dec-Feb
                                                   21         Sep-Nov
Encore at wynn Las Vegas                           279        Jun-Aug
                                                   264        Dec-Feb
Excalibur Hotel & Casino                           26         Dec-Feb
                                                   39         Jun-Aug
Hilton Grand Vacations at the Flamingo             364        Mar-May
                                                   363        Dec-Feb
Hilton Grand Vacations on the Boulevard            310        Dec-Feb
                                                   297        Mar-May
Marriott's Grand Chateau                           314        Dec-Feb
                                                   330        Sep-Nov
Monte Carlo Resort&Casino                          54         Mar-May
                                                   69         Sep-Nov
Paris Las Vegas                                    457        Dec-Feb
                                                   458        Dec-Feb
The Cosmopolitan Las Vegas                         160        Sep-Nov
                                                   156        Jun-Aug
The Cromwell                                       251        Jun-Aug
                                                   253        Jun-Aug
The Palazzo Resort Hotel Casino                    170        Dec-Feb
                                                   168        Dec-Feb
The Venetian Las Vegas Hotel                       413        Mar-May
                                                   412        Mar-May
The Westin las Vegas Hotel Casino & Spa            484        Mar-May
                                                   502        Dec-Feb
Treasure Island- TI Hotel & Casino                 92         Sep-Nov
                                                   79         Mar-May
Tropicana Las Vegas - A Double Tree by Hilton H... 110        Jun-Aug
                                                   112        Sep-Nov
Trump International Hotel Las Vegas                223        Mar-May
                                                   233        Sep-Nov
Tuscany Las Vegas Suites & Casino                  336        Dec-Feb
                                                   344        Mar-May
Wyndham Grand Desert                               390        Mar-May
                                                   402        Sep-Nov
Wynn Las Vegas                                     198        Mar-May
                                                   208        Sep-Nov

                                                       traveler_type pool  \
hotel_name
Bellagio Las Vegas                                 436       Couples  YES
                                                   455      Families  YES
Caesars Palace                                     126       Couples  YES
                                                   131          Solo  YES
Circus Circus Hotel & Casino Las Vegas             0         Friends   NO
                                                   21        Couples   NO
Encore at wynn Las Vegas                           279      Families  YES
                                                   264      Business  YES
Excalibur Hotel & Casino                           26        Couples  YES
                                                   39       Families  YES
Hilton Grand Vacations at the Flamingo             364       Friends  YES
                                                   363      Families  YES
Hilton Grand Vacations on the Boulevard            310       Couples  YES
                                                   297       Couples  YES
Marriott's Grand Chateau                           314      Families  YES
                                                   330      Business  YES
Monte Carlo Resort&Casino                          54        Couples  YES
                                                   69       Business  YES
Paris Las Vegas                                    457       Couples  YES
                                                   458       Couples  YES
The Cosmopolitan Las Vegas                         160       Couples  YES
                                                   156      Business  YES
The Cromwell                                       251       Couples  YES
                                                   253       Friends  YES
The Palazzo Resort Hotel Casino                    170       Couples  YES
                                                   168       Couples  YES
The Venetian Las Vegas Hotel                       413       Couples  YES
                                                   412       Couples  YES
The Westin las Vegas Hotel Casino & Spa            484      Business  YES
                                                   502      Families  YES
Treasure Island- TI Hotel & Casino                 92        Couples  YES
                                                   79       Families  YES
Tropicana Las Vegas - A Double Tree by Hilton H... 110       Friends  YES
                                                   112       Couples  YES
Trump International Hotel Las Vegas                223       Couples  YES
                                                   233      Families  YES
Tuscany Las Vegas Suites & Casino                  336       Couples  YES
                                                   344      Families  YES
Wyndham Grand Desert                               390      Families  YES
                                                   402       Couples  YES
Wynn Las Vegas                                     198      Business  YES
                                                   208      Business  YES

                                                        gym tennis_court  spa  \
hotel_name
Bellagio Las Vegas                                 436  YES           NO  YES
                                                   455  YES           NO  YES
Caesars Palace                                     126  YES           NO  YES
                                                   131  YES           NO  YES
Circus Circus Hotel & Casino Las Vegas             0    YES           NO   NO
                                                   21   YES           NO   NO
Encore at wynn Las Vegas                           279  YES           NO  YES
                                                   264  YES           NO  YES
Excalibur Hotel & Casino                           26   YES           NO  YES
                                                   39   YES           NO  YES
Hilton Grand Vacations at the Flamingo             364  YES           NO   NO
                                                   363  YES           NO   NO
Hilton Grand Vacations on the Boulevard            310  YES           NO  YES
                                                   297  YES           NO  YES
Marriott's Grand Chateau                           314  YES           NO   NO
                                                   330  YES           NO   NO
Monte Carlo Resort&Casino                          54   YES           NO  YES

In [12]:
by_hotel.apply(top_bottom_reviewers)

                                                       user_country  \
hotel_name
Bellagio Las Vegas                                 441           UK
                                                   437          USA
Caesars Palace                                     137          USA
                                                   131          USA
Circus Circus Hotel & Casino Las Vegas             2            USA
                                                   21    New Zeland
Encore at wynn Las Vegas                           268          USA
                                                   264     Thailand
Excalibur Hotel & Casino                           29       Ireland
                                                   39           USA
Hilton Grand Vacations at the Flamingo             365       Hawaii
                                                   363          USA
Hilton Grand Vacations on the Boulevard            292           UK
                                                   297          USA
Marriott's Grand Chateau                           326       Taiwan
                                                   330     Thailand
Monte Carlo Resort&Casino                          54      Scotland
                                                   69         China
Paris Las Vegas                                    475          USA
                                                   458          USA
The Cosmopolitan Las Vegas                         160           UK
                                                   156          USA
The Cromwell                                       249          USA
                                                   253          USA
The Palazzo Resort Hotel Casino                    181          USA
                                                   184           UK
The Venetian Las Vegas Hotel                       425           UK
                                                   412          USA
The Westin las Vegas Hotel Casino & Spa            496          USA
                                                   502          USA
Treasure Island- TI Hotel & Casino                 95        Canada
                                                   72       Croatia
Tropicana Las Vegas - A Double Tree by Hilton H... 110   New Zeland
                                                   112       Canada
Trump International Hotel Las Vegas                232           UK
                                                   233        Egypt
Tuscany Las Vegas Suites & Casino                  339          USA
                                                   344        India
Wyndham Grand Desert                               388          USA
                                                   398          USA
Wynn Las Vegas                                     193          USA
                                                   208       Canada

                                                        nr_reviews  \
hotel_name
Bellagio Las Vegas                                 441          15
                                                   437          30
Caesars Palace                                     137          10
                                                   131          25
Circus Circus Hotel & Casino Las Vegas             2            36
                                                   21            4
Encore at wynn Las Vegas                           268          16
                                                   264           3
Excalibur Hotel & Casino                           29            8
                                                   39           24
Hilton Grand Vacations at the Flamingo             365           9
                                                   363           3
Hilton Grand Vacations on the Boulevard            292          60
                                                   297          70
Marriott's Grand Chateau                           326          20
                                                   330          18
Monte Carlo Resort&Casino                          54           24
                                                   69            1
Paris Las Vegas                                    475           6
                                                   458           4
The Cosmopolitan Las Vegas                         160          18
                                                   156           6
The Cromwell                                       249          59
                                                   253           4
The Palazzo Resort Hotel Casino                    181          20
                                                   184          52
The Venetian Las Vegas Hotel                       425          29
                                                   412           9
The Westin las Vegas Hotel Casino & Spa            496          30
                                                   502           9
Treasure Island- TI Hotel & Casino                 95           21
                                                   72           29
Tropicana Las Vegas - A Double Tree by Hilton H... 110           8
                                                   112          27
Trump International Hotel Las Vegas                232          24
                                                   233           2
Tuscany Las Vegas Suites & Casino                  339         608
                                                   344           1
Wyndham Grand Desert                               388          27
                                                   398          41
Wynn Las Vegas                                     193           5
                                                   208          12

                                                        nr_hotel_reviews  \
hotel_name
Bellagio Las Vegas                                 441                 6
                                                   437                 9
Caesars Palace                                     137                 7
                                                   131                22
Circus Circus Hotel & Casino Las Vegas             2                   9
                                                   21                  3
Encore at wynn Las Vegas                           268                14
                                                   264                 3
Excalibur Hotel & Casino                           29                  7
                                                   39                  6
Hilton Grand Vacations at the Flamingo             365                 7
                                                   363                 3
Hilton Grand Vacations on the Boulevard            292                 7
                                                   297                25
Marriott's Grand Chateau                           326                12
                                                   330                 9
Monte Carlo Resort&Casino                          54                 10
                                                   69                  0
Paris Las Vegas                                    475                 4
                                                   458                 4
The Cosmopolitan Las Vegas                         160                 9
                                                   156                 4
The Cromwell                                       249                 9
                                                   253                 0
The Palazzo Resort Hotel Casino                    181                11
                                                   184                48
The Venetian Las Vegas Hotel                       425                 7
                                                   412                 3
The Westin las Vegas Hotel Casino & Spa            496                27
                                                   502                 6
Treasure Island- TI Hotel & Casino                 95                 16
                                                   72                 11
Tropicana Las Vegas - A Double Tree by Hilton H... 110                 7
                                                   112                 0
Trump International Hotel Las Vegas                232                18
                                                   233                 0
Tuscany Las Vegas Suites & Casino                  339               117
                                                   344                 0
Wyndham Grand Desert                               388                12
                                                   398                 8
Wynn Las Vegas                                     193                 3
                                                   208                 7

                                                        helpful_votes  score  \
hotel_name
Bellagio Las Vegas                                 441             17      5
                                                   437             17      2
Caesars Palace                                     137              7      5
                                                   131             36      1
Circus Circus Hotel & Casino Las Vegas             2               25      5
                                                   21               3      1
Encore at wynn Las Vegas                           268             23      5
                                                   264             20      1
Excalibur Hotel & Casino                           29               9      5
                                                   39               9      2
Hilton Grand Vacations at the Flamingo             365              4      5
                                                   363              8      2
Hilton Grand Vacations on the Boulevard            292             42      5
                                                   297             19      1
Marriott's Grand Chateau                           326              7      5
                                                   330              8      3
Monte Carlo Resort&Casino                          54              13      5
                                                   69               2      1
Paris Las Vegas                                    475              6      5
                                                   458              2      2
The Cosmopolitan Las Vegas                         160             10      5
                                                   156             14      1
The Cromwell                                       249             21      5
                                                   253             16      1
The Palazzo Resort Hotel Casino                    181             21      5
                                                   184             78      3
The Venetian Las Vegas Hotel                       425             15      5
                                                   412             13      3
The Westin las Vegas Hotel Casino & Spa            496             19      5
                                                   502              5      2
Treasure Island- TI Hotel & Casino                 95              48      5
                                                   72              14      3
Tropicana Las Vegas - A Double Tree by Hilton H... 110              3      5
                                                   112              9      1
Trump International Hotel Las Vegas                232             12      5
                                                   233             15      1
Tuscany Las Vegas Suites & Casino                  339            319      5
                                                   344              3      2
Wyndham Grand Desert                               388             51      5
                                                   398             14      3
Wynn Las Vegas                                     193              9      5
                                                   208             11      2

                                                       period_of_stay  \
hotel_name
Bellagio Las Vegas                                 441        Mar-May
                                                   437        Mar-May
Caesars Palace                                     137        Sep-Nov
                                                   131        Jun-Aug
Circus Circus Hotel & Casino Las Vegas             2          Mar-May
                                                   21         Sep-Nov
Encore at wynn Las Vegas                           268        Mar-May
                                                   264        Dec-Feb
Excalibur Hotel & Casino                           29         Mar-May
                                                   39         Jun-Aug
Hilton Grand Vacations at the Flamingo             365        Mar-May
                                                   363        Dec-Feb
Hilton Grand Vacations on the Boulevard            292        Mar-May
                                                   297        Mar-May
Marriott's Grand Chateau                           326        Jun-Aug
                                                   330        Sep-Nov
Monte Carlo Resort&Casino                          54         Mar-May
                                                   69         Sep-Nov
Paris Las Vegas                                    475        Sep-Nov
                                                   458        Dec-Feb
The Cosmopolitan Las Vegas                         160        Sep-Nov
                                                   156        Jun-Aug
The Cromwell                                       249        Mar-May
                                                   253        Jun-Aug
The Palazzo Resort Hotel Casino                    181        Jun-Aug
                                                   184        Sep-Nov
The Venetian Las Vegas Hotel                       425        Sep-Nov
                                                   412        Mar-May
The Westin las Vegas Hotel Casino & Spa            496        Sep-Nov
                                                   502        Dec-Feb
Treasure Island- TI Hotel & Casino                 95         Dec-Feb
                                                   72         Dec-Feb
Tropicana Las Vegas - A Double Tree by Hilton H... 110        Jun-Aug
                                                   112        Sep-Nov
Trump International Hotel Las Vegas                232        Sep-Nov
                                                   233        Sep-Nov
Tuscany Las Vegas Suites & Casino                  339        Dec-Feb
                                                   344        Mar-May
Wyndham Grand Desert                               388        Mar-May
                                                   398        Jun-Aug
Wynn Las Vegas                                     193        Dec-Feb
                                                   208        Sep-Nov

                                                       traveler_type pool  \
hotel_name
Bellagio Las Vegas                                 441       Couples  YES
                                                   437      Business  YES
Caesars Palace                                     137       Couples  YES
                                                   131          Solo  YES
Circus Circus Hotel & Casino Las Vegas             2        Families   NO
                                                   21        Couples   NO
Encore at wynn Las Vegas                           268       Couples  YES
                                                   264      Business  YES
Excalibur Hotel & Casino                           29        Couples  YES
                                                   39       Families  YES
Hilton Grand Vacations at the Flamingo             365       Couples  YES
                                                   363      Families  YES
Hilton Grand Vacations on the Boulevard            292       Couples  YES
                                                   297       Couples  YES
Marriott's Grand Chateau                           326      Families  YES
                                                   330      Business  YES
Monte Carlo Resort&Casino                          54        Couples  YES
                                                   69       Business  YES
Paris Las Vegas                                    475       Couples  YES
                                                   458       Couples  YES
The Cosmopolitan Las Vegas                         160       Couples  YES
                                                   156      Business  YES
The Cromwell                                       249       Couples  YES
                                                   253       Friends  YES
The Palazzo Resort Hotel Casino                    181      Families  YES
                                                   184       Friends  YES
The Venetian Las Vegas Hotel                       425       Couples  YES
                                                   412       Couples  YES
The Westin las Vegas Hotel Casino & Spa            496          Solo  YES
                                                   502      Families  YES
Treasure Island- TI Hotel & Casino                 95        Couples  YES
                                                   72       Business  YES
Tropicana Las Vegas - A Double Tree by Hilton H... 110       Friends  YES
                                                   112       Couples  YES
Trump International Hotel Las Vegas                232      Families  YES
                                                   233      Families  YES
Tuscany Las Vegas Suites & Casino                  339      Business  YES
                                                   344      Families  YES
Wyndham Grand Desert                               388       Friends  YES
                                                   398      Families  YES
Wynn Las Vegas                                     193      Families  YES
                                                   208      Business  YES

                                                        gym tennis_court  spa  \
hotel_name
Bellagio Las Vegas                                 441  YES           NO  YES
                                                   437  YES           NO  YES
Caesars Palace                                     137  YES           NO  YES
                                                   131  YES           NO  YES
Circus Circus Hotel & Casino Las Vegas             2    YES           NO   NO
                                                   21   YES           NO   NO
Encore at wynn Las Vegas                           268  YES           NO  YES
                                                   264  YES           NO  YES
Excalibur Hotel & Casino                           29   YES           NO  YES
                                                   39   YES           NO  YES
Hilton Grand Vacations at the Flamingo             365  YES           NO   NO
                                                   363  YES           NO   NO
Hilton Grand Vacations on the Boulevard            292  YES           NO  YES
                                                   297  YES           NO  YES
Marriott's Grand Chateau                           326  YES           NO   NO
                                                   330  YES           NO   NO
Monte Carlo Resort&Casino                          54   YES           NO  YES